param(
  [string]$BaseUrl = "http://localhost:3000",
  [string]$WebhookUrl = "",
  [switch]$CreateWebhookChannel,
  [switch]$ForceFailedWebhook
)

$ErrorActionPreference = "Stop"

function Write-Step {
  param([string]$Message)
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Invoke-JsonApi {
  param(
    [string]$Method = "GET",
    [string]$Path,
    [object]$Body = $null
  )

  $uri = "$BaseUrl$Path"
  $upperMethod = $Method.ToUpperInvariant()

  if ($null -eq $Body -and $upperMethod -eq "GET") {
    return Invoke-RestMethod -Method $Method -Uri $uri
  }

  if ($null -eq $Body) {
    $Body = @{}
  }

  $json = $Body | ConvertTo-Json -Depth 30

  return Invoke-RestMethod `
    -Method $Method `
    -Uri $uri `
    -ContentType "application/json" `
    -Body $json
}

function Get-FirstRetryableDeliveryId {
  param([object[]]$Deliveries)

  foreach ($item in $Deliveries) {
    if ($item.status -eq "failed" -or $item.status -eq "skipped") {
      return $item.id
    }
  }

  return ""
}

Write-Host "Notification Engine Smoke Test" -ForegroundColor Green
Write-Host "BaseUrl: $BaseUrl"

Write-Step "Seed default notification channel and rule"
$seed = Invoke-JsonApi -Method "POST" -Path "/api/v1/notifications/seed-defaults" -Body @{}
$seed | ConvertTo-Json -Depth 30

if ($CreateWebhookChannel -and $WebhookUrl.Trim().Length -gt 0) {
  Write-Step "Create webhook notification channel"
  $webhookChannel = Invoke-JsonApi `
    -Method "POST" `
    -Path "/api/v1/notifications/channels" `
    -Body @{
      name = "Smoke Test Webhook"
      type = "webhook"
      enabled = $true
      config = @{
        url = $WebhookUrl
        method = "POST"
        timeoutMs = 10000
        headers = @{
          "x-source" = "mikrotik-manager-enterprise"
          "x-smoke-test" = "notification-engine"
        }
      }
    }

  $webhookChannel | ConvertTo-Json -Depth 30

  $channelId = $webhookChannel.data.id

  Write-Step "Create webhook notification rule"
  $webhookRule = Invoke-JsonApi `
    -Method "POST" `
    -Path "/api/v1/notifications/rules" `
    -Body @{
      name = "Smoke Test Webhook Rule"
      enabled = $true
      eventTypes = @("ALERT_OPENED", "DEVICE_OFFLINE")
      severities = @("critical", "warning")
      channelIds = @($channelId)
    }

  $webhookRule | ConvertTo-Json -Depth 30
}

if ($ForceFailedWebhook) {
  Write-Step "Create intentionally failing webhook channel"
  $badWebhookChannel = Invoke-JsonApi `
    -Method "POST" `
    -Path "/api/v1/notifications/channels" `
    -Body @{
      name = "Smoke Test Failing Webhook"
      type = "webhook"
      enabled = $true
      config = @{
        url = "http://127.0.0.1:1/unreachable"
        method = "POST"
        timeoutMs = 1000
        headers = @{
          "x-source" = "mikrotik-manager-enterprise"
          "x-smoke-test" = "notification-engine-failure"
        }
      }
    }

  $badWebhookChannel | ConvertTo-Json -Depth 30

  $badChannelId = $badWebhookChannel.data.id

  Write-Step "Create intentionally failing webhook rule"
  $badWebhookRule = Invoke-JsonApi `
    -Method "POST" `
    -Path "/api/v1/notifications/rules" `
    -Body @{
      name = "Smoke Test Failing Webhook Rule"
      enabled = $true
      eventTypes = @("ALERT_OPENED")
      severities = @("critical")
      channelIds = @($badChannelId)
    }

  $badWebhookRule | ConvertTo-Json -Depth 30
}

Write-Step "List notification channels"
$channels = Invoke-JsonApi -Path "/api/v1/notifications/channels"
$channels | ConvertTo-Json -Depth 30

Write-Step "List notification rules"
$rules = Invoke-JsonApi -Path "/api/v1/notifications/rules"
$rules | ConvertTo-Json -Depth 30

Write-Step "Queue notification test payload"
$test = Invoke-JsonApi `
  -Method "POST" `
  -Path "/api/v1/notifications/test" `
  -Body @{
    eventType = "ALERT_OPENED"
    severity = "critical"
    title = "Notification smoke test"
    message = "This payload was generated by tools/smoke-tests/notification-smoke.ps1"
    source = "notification-smoke-test"
    metadata = @{
      smokeTest = $true
      generatedBy = "PowerShell"
    }
  }

$test | ConvertTo-Json -Depth 30

Write-Step "Process pending notification deliveries"
$processed = Invoke-JsonApi `
  -Method "POST" `
  -Path "/api/v1/notifications/process-pending" `
  -Body @{
    limit = 50
  }

$processed | ConvertTo-Json -Depth 30

Write-Step "Retry all failed/skipped notification deliveries"
$retryFailed = Invoke-JsonApi `
  -Method "POST" `
  -Path "/api/v1/notifications/retry-failed" `
  -Body @{
    limit = 50
  }

$retryFailed | ConvertTo-Json -Depth 30

Write-Step "Recent deliveries"
$deliveriesResponse = Invoke-JsonApi -Path "/api/v1/notifications/deliveries?limit=20"
$deliveriesResponse | ConvertTo-Json -Depth 30

$retryableId = Get-FirstRetryableDeliveryId -Deliveries $deliveriesResponse.data

if ($retryableId.Trim().Length -gt 0) {
  Write-Step "Retry one delivery: $retryableId"
  $singleRetry = Invoke-JsonApi `
    -Method "POST" `
    -Path "/api/v1/notifications/deliveries/$retryableId/retry" `
    -Body @{}

  $singleRetry | ConvertTo-Json -Depth 30
}
else {
  Write-Step "No failed/skipped delivery found for single retry"
}

Write-Step "Notification summary"
$summary = Invoke-JsonApi -Path "/api/v1/notifications/summary"
$summary | ConvertTo-Json -Depth 30

Write-Step "Done"
Write-Host "Notification smoke test completed." -ForegroundColor Green
