import { RouterOsPrintCollector } from './routeros-print.collector.js';

export const defaultInventoryCollectors = [
  new RouterOsPrintCollector({
    key: 'system.identity',
    category: 'system',
    label: 'Identity',
    path: '/system/identity/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.resource',
    category: 'system',
    label: 'Resource',
    path: '/system/resource/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.routerboard',
    category: 'system',
    label: 'RouterBOARD',
    path: '/system/routerboard/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.health',
    category: 'system',
    label: 'Health Sensors',
    path: '/system/health/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.note',
    category: 'system',
    label: 'System Note',
    path: '/system/note/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.license',
    category: 'system',
    label: 'License',
    path: '/system/license/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.packages',
    category: 'system',
    label: 'Packages',
    path: '/system/package/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.clock',
    category: 'system',
    label: 'Clock',
    path: '/system/clock/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.users',
    category: 'system',
    label: 'Users',
    path: '/user/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.files',
    category: 'system',
    label: 'Files',
    path: '/file/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.logs',
    category: 'system',
    label: 'Logs',
    path: '/log/print',
    enabledByDefault: false,
  }),
  new RouterOsPrintCollector({
    key: 'interfaces.all',
    category: 'interfaces',
    label: 'Interfaces',
    path: '/interface/print',
  }),
  new RouterOsPrintCollector({
    key: 'interfaces.ethernet',
    category: 'interfaces',
    label: 'Ethernet Details',
    path: '/interface/ethernet/print',
  }),
  new RouterOsPrintCollector({
    key: 'interfaces.bridge',
    category: 'interfaces',
    label: 'Bridge',
    path: '/interface/bridge/print',
  }),
  new RouterOsPrintCollector({
    key: 'interfaces.bridge-port',
    category: 'interfaces',
    label: 'Bridge Ports',
    path: '/interface/bridge/port/print',
  }),
  new RouterOsPrintCollector({
    key: 'interfaces.vlan',
    category: 'interfaces',
    label: 'VLAN',
    path: '/interface/vlan/print',
  }),
  new RouterOsPrintCollector({
    key: 'interfaces.wireguard',
    category: 'interfaces',
    label: 'WireGuard',
    path: '/interface/wireguard/print',
  }),
  new RouterOsPrintCollector({
    key: 'ip.address',
    category: 'ip',
    label: 'IP Address',
    path: '/ip/address/print',
  }),
  new RouterOsPrintCollector({
    key: 'ip.dhcp-client',
    category: 'ip',
    label: 'DHCP Client',
    path: '/ip/dhcp-client/print',
  }),
  new RouterOsPrintCollector({
    key: 'ip.dhcp-server',
    category: 'ip',
    label: 'DHCP Server',
    path: '/ip/dhcp-server/print',
  }),
  new RouterOsPrintCollector({
    key: 'ip.dhcp-lease',
    category: 'ip',
    label: 'DHCP Lease',
    path: '/ip/dhcp-server/lease/print',
  }),
  new RouterOsPrintCollector({
    key: 'ip.arp',
    category: 'ip',
    label: 'ARP',
    path: '/ip/arp/print',
  }),
  new RouterOsPrintCollector({
    key: 'ip.dns',
    category: 'ip',
    label: 'DNS',
    path: '/ip/dns/print',
  }),
  new RouterOsPrintCollector({
    key: 'discovery.neighbors',
    category: 'discovery',
    label: 'RouterOS Neighbors',
    path: '/ip/neighbor/print',
  }),
  new RouterOsPrintCollector({
    key: 'discovery.bridge-hosts',
    category: 'discovery',
    label: 'Bridge Forwarding Hosts',
    path: '/interface/bridge/host/print',
    optional: true,
    attempts: 1,
    timeoutMs: 7000,
  }),
  new RouterOsPrintCollector({
    key: 'discovery.wifi-registrations',
    category: 'discovery',
    label: 'WiFi Registrations',
    path: '/interface/wifi/registration-table/print',
    optional: true,
    attempts: 1,
    timeoutMs: 7000,
  }),
  new RouterOsPrintCollector({
    key: 'discovery.wifiwave2-registrations',
    category: 'discovery',
    label: 'WiFiWave2 Registrations',
    path: '/interface/wifiwave2/registration-table/print',
    optional: true,
    attempts: 1,
    timeoutMs: 7000,
  }),
  new RouterOsPrintCollector({
    key: 'discovery.wireless-registrations',
    category: 'discovery',
    label: 'Legacy Wireless Registrations',
    path: '/interface/wireless/registration-table/print',
    optional: true,
    attempts: 1,
    timeoutMs: 7000,
  }),
  new RouterOsPrintCollector({
    key: 'discovery.capsman-registrations',
    category: 'discovery',
    label: 'CAPsMAN Registrations',
    path: '/caps-man/registration-table/print',
    optional: true,
    attempts: 1,
    timeoutMs: 7000,
  }),
  new RouterOsPrintCollector({
    key: 'discovery.ospf-neighbors',
    category: 'discovery',
    label: 'OSPF Neighbors',
    path: '/routing/ospf/neighbor/print',
    optional: true,
    attempts: 1,
    timeoutMs: 7000,
  }),
  new RouterOsPrintCollector({
    key: 'routing.routes',
    category: 'routing',
    label: 'Route List',
    path: '/ip/route/print',
  }),
  new RouterOsPrintCollector({
    key: 'routing.tables',
    category: 'routing',
    label: 'Routing Tables',
    path: '/routing/table/print',
  }),
  new RouterOsPrintCollector({
    key: 'routing.rules',
    category: 'routing',
    label: 'Routing Rules',
    path: '/routing/rule/print',
  }),
  new RouterOsPrintCollector({
    key: 'routing.ospf',
    category: 'routing',
    label: 'OSPF',
    path: '/routing/ospf/instance/print',
    enabledByDefault: false,
  }),
  new RouterOsPrintCollector({
    key: 'routing.bgp',
    category: 'routing',
    label: 'BGP',
    path: '/routing/bgp/connection/print',
    enabledByDefault: false,
  }),
  new RouterOsPrintCollector({
    key: 'firewall.filter',
    category: 'firewall',
    label: 'Filter',
    path: '/ip/firewall/filter/print',
  }),
  new RouterOsPrintCollector({
    key: 'firewall.nat',
    category: 'firewall',
    label: 'NAT',
    path: '/ip/firewall/nat/print',
  }),
  new RouterOsPrintCollector({
    key: 'firewall.mangle',
    category: 'firewall',
    label: 'Mangle',
    path: '/ip/firewall/mangle/print',
  }),
  new RouterOsPrintCollector({
    key: 'firewall.address-list',
    category: 'firewall',
    label: 'Address Lists',
    path: '/ip/firewall/address-list/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.hotspot',
    category: 'services',
    label: 'Hotspot',
    path: '/ip/hotspot/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.ppp-secret',
    category: 'services',
    label: 'PPP Secrets',
    path: '/ppp/secret/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.pppoe-server',
    category: 'services',
    label: 'PPPoE Server',
    path: '/interface/pppoe-server/server/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.l2tp',
    category: 'services',
    label: 'L2TP',
    path: '/interface/l2tp-server/server/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.pptp',
    category: 'services',
    label: 'PPTP',
    path: '/interface/pptp-server/server/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.sstp',
    category: 'services',
    label: 'SSTP',
    path: '/interface/sstp-server/server/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.ovpn',
    category: 'services',
    label: 'OpenVPN',
    path: '/interface/ovpn-server/server/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.ipsec',
    category: 'services',
    label: 'IPsec',
    path: '/ip/ipsec/profile/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.radius',
    category: 'services',
    label: 'RADIUS',
    path: '/radius/print',
  }),
  new RouterOsPrintCollector({
    key: 'services.user-manager',
    category: 'services',
    label: 'User Manager',
    path: '/tool/user-manager/user/print',
    enabledByDefault: false,
  }),
  new RouterOsPrintCollector({
    key: 'services.ip-service',
    category: 'services',
    label: 'IP Services',
    path: '/ip/service/print',
  }),
  new RouterOsPrintCollector({
    key: 'automation.scripts',
    category: 'automation',
    label: 'Scripts',
    path: '/system/script/print',
  }),
  new RouterOsPrintCollector({
    key: 'automation.scheduler',
    category: 'automation',
    label: 'Scheduler',
    path: '/system/scheduler/print',
  }),
  new RouterOsPrintCollector({
    key: 'automation.netwatch',
    category: 'automation',
    label: 'Netwatch',
    path: '/tool/netwatch/print',
  }),
  new RouterOsPrintCollector({
    key: 'system.romon',
    category: 'system',
    label: 'RoMON',
    path: '/tool/romon/print',
    enabledByDefault: false,
  }),
  new RouterOsPrintCollector({
    key: 'qos.simple-queue',
    category: 'qos',
    label: 'Simple Queue',
    path: '/queue/simple/print',
  }),
  new RouterOsPrintCollector({
    key: 'qos.queue-tree',
    category: 'qos',
    label: 'Queue Tree',
    path: '/queue/tree/print',
  }),
  new RouterOsPrintCollector({
    key: 'containers.list',
    category: 'containers',
    label: 'Containers',
    path: '/container/print',
    enabledByDefault: false,
  }),
];
